#!/bin/bash
# Echo-Mate AArch64 一键交叉编译脚本
# 用于 Ubuntu 24.04 容器环境

set -e

echo "=========================================="
echo "Echo-Mate AArch64 交叉编译脚本"
echo "=========================================="

# 检查是否在容器中
if [ ! -f /.dockerenv ]; then
    echo "警告: 此脚本应在 Docker 容器中运行"
    echo "请使用: docker exec -it ubuntu2404-build bash"
    exit 1
fi

# 设置交叉编译环境变量
echo ""
echo "[1/5] 设置交叉编译环境变量..."
export ARCH=aarch64
export CROSS_COMPILE=aarch64-linux-gnu-

# 强制使用 AArch64 头文件路径
export C_INCLUDE_PATH=/usr/aarch64-linux-gnu/include:/usr/lib/gcc-cross/aarch64-linux-gnu/13/include
export CPLUS_INCLUDE_PATH=/usr/aarch64-linux-gnu/include:/usr/lib/gcc-cross/aarch64-linux-gnu/13/include:/usr/lib/gcc-cross/aarch64-linux-gnu/13/include/c++:/usr/lib/gcc-cross/aarch64-linux-gnu/13/include/c++/aarch64-linux-gnu

# 库路径
export LIBRARY_PATH=/usr/aarch64-linux-gnu/lib:/usr/lib/gcc-cross/aarch64-linux-gnu/13

# 编译器标志 - 不使用 --sysroot，只使用 -isystem 和 -I
export CFLAGS="-march=armv8-a -I/usr/aarch64-linux-gnu/include -I/usr/lib/gcc-cross/aarch64-linux-gnu/13/include"
export CXXFLAGS="-march=armv8-a -I/usr/aarch64-linux-gnu/include -I/usr/lib/gcc-cross/aarch64-linux-gnu/13/include -I/usr/lib/gcc-cross/aarch64-linux-gnu/13/include/c++ -I/usr/lib/gcc-cross/aarch64-linux-gnu/13/include/c++/aarch64-linux-gnu"
export LDFLAGS="-L/usr/aarch64-linux-gnu/lib -L/usr/lib/gcc-cross/aarch64-linux-gnu/13"

echo "C compiler: $(which aarch64-linux-gnu-gcc)"
echo "C++ compiler: $(which aarch64-linux-gnu-g++)"

# 修复头文件
echo ""
echo "[2/5] 修复头文件路径..."

# 确保 AArch64 的 curl 头文件存在
if [ ! -d /usr/aarch64-linux-gnu/include/curl ]; then
    echo "  创建 curl 头文件..."
    mkdir -p /usr/aarch64-linux-gnu/include/curl
    cp -r /usr/include/x86_64-linux-gnu/curl/*.h /usr/aarch64-linux-gnu/include/curl/ 2>/dev/null || true
fi

# 修复 stubs.h 问题
echo "  修复 stubs.h..."
mkdir -p /usr/aarch64-linux-gnu/include/gnu
cat > /usr/aarch64-linux-gnu/include/gnu/stubs.h << 'EOF'
/* This file is automatically generated.  DO NOT EDIT! */
/* This file is for AArch64 */
#include <gnu/stubs-lp64.h>
EOF

echo ""
echo "[3/5] 编译 yolov5_demo..."
cd /project/Demo/yolov5_demo/cpp
rm -rf build_aarch64
mkdir -p build_aarch64
cd build_aarch64
cmake .. \
    -DCMAKE_TOOLCHAIN_FILE=../toolchain-aarch64.cmake \
    -DCMAKE_C_COMPILER=/usr/bin/aarch64-linux-gnu-gcc \
    -DCMAKE_CXX_COMPILER=/usr/bin/aarch64-linux-gnu-g++ \
    -DCMAKE_C_FLAGS="$CFLAGS" \
    -DCMAKE_CXX_FLAGS="$CXXFLAGS" \
    -DCMAKE_EXE_LINKER_FLAGS="$LDFLAGS" \
    -DCMAKE_SYSTEM_PROCESSOR=aarch64
make -j$(nproc) 2>&1 | tail -20
echo "  ✓ yolov5_demo 编译完成"

echo ""
echo "[4/5] 编译 AIChat_demo/Client..."
cd /project/Demo/AIChat_demo/Client
rm -rf build_aarch64
mkdir -p build_aarch64
cd build_aarch64
cmake .. \
    -DTARGET_AARCH64=ON \
    -DCMAKE_C_COMPILER=/usr/bin/aarch64-linux-gnu-gcc \
    -DCMAKE_CXX_COMPILER=/usr/bin/aarch64-linux-gnu-g++ \
    -DCMAKE_C_FLAGS="$CFLAGS" \
    -DCMAKE_CXX_FLAGS="$CXXFLAGS" \
    -DCMAKE_EXE_LINKER_FLAGS="$LDFLAGS" \
    -DCMAKE_SYSTEM_PROCESSOR=aarch64
make -j$(nproc) 2>&1 | tail -20
echo "  ✓ AIChat_demo/Client 编译完成"

echo ""
echo "[5/5] 编译 DeskBot_demo..."
cd /project/Demo/DeskBot_demo
rm -rf build_aarch64
mkdir -p build_aarch64
cd build_aarch64
cmake .. \
    -DTARGET_AARCH64=ON \
    -DCMAKE_C_COMPILER=/usr/bin/aarch64-linux-gnu-gcc \
    -DCMAKE_CXX_COMPILER=/usr/bin/aarch64-linux-gnu-g++ \
    -DCMAKE_C_FLAGS="$CFLAGS" \
    -DCMAKE_CXX_FLAGS="$CXXFLAGS" \
    -DCMAKE_EXE_LINKER_FLAGS="$LDFLAGS" \
    -DCMAKE_SYSTEM_PROCESSOR=aarch64
make -j$(nproc) 2>&1 | tail -30
echo "  ✓ DeskBot_demo 编译完成"

echo ""
echo "=========================================="
echo "编译完成!"
echo "=========================================="
echo ""
echo "输出文件:"
echo "  - yolov5_demo: /project/Demo/yolov5_demo/cpp/build_aarch64/rknn_yolov5_demo"
echo "  - AIChat_demo: /project/Demo/AIChat_demo/Client/build_aarch64/AIChatClient"
echo "  - DeskBot_demo: /project/Demo/DeskBot_demo/build_aarch64/main"
echo ""
echo "验证文件类型:"
aarch64-linux-gnu-file /project/Demo/yolov5_demo/cpp/build_aarch64/rknn_yolov5_demo 2>/dev/null || true
aarch64-linux-gnu-file /project/Demo/DeskBot_demo/build_aarch64/main 2>/dev/null || true
