#!/bin/bash
# Echo-Mate AArch64 完整编译和部署准备脚本
# 编译所有项目并自动复制所有依赖库到输出目录

set -e

echo "=========================================="
echo "Echo-Mate AArch64 完整编译脚本"
echo "=========================================="

# 检查是否在容器中
if [ ! -f /.dockerenv ]; then
    echo "警告: 此脚本应在 Docker 容器中运行"
    echo "请使用: docker exec -it ubuntu2404-build bash"
    exit 1
fi

# 设置交叉编译环境变量
echo ""
echo "[1/6] 设置交叉编译环境变量..."
export ARCH=aarch64
export CROSS_COMPILE=aarch64-linux-gnu-

# 强制使用 AArch64 头文件路径
export C_INCLUDE_PATH=/usr/aarch64-linux-gnu/include:/usr/lib/gcc-cross/aarch64-linux-gnu/13/include
export CPLUS_INCLUDE_PATH=/usr/aarch64-linux-gnu/include:/usr/lib/gcc-cross/aarch64-linux-gnu/13/include:/usr/lib/gcc-cross/aarch64-linux-gnu/13/include/c++:/usr/lib/gcc-cross/aarch64-linux-gnu/13/include/c++/aarch64-linux-gnu

# 库路径
export LIBRARY_PATH=/usr/aarch64-linux-gnu/lib:/usr/lib/gcc-cross/aarch64-linux-gnu/13

# 编译器标志
export CFLAGS="-march=armv8-a -I/usr/aarch64-linux-gnu/include -I/usr/lib/gcc-cross/aarch64-linux-gnu/13/include"
export CXXFLAGS="-march=armv8-a -I/usr/aarch64-linux-gnu/include -I/usr/lib/gcc-cross/aarch64-linux-gnu/13/include -I/usr/lib/gcc-cross/aarch64-linux-gnu/13/include/c++ -I/usr/lib/gcc-cross/aarch64-linux-gnu/13/include/c++/aarch64-linux-gnu"
export LDFLAGS="-L/usr/aarch64-linux-gnu/lib -L/usr/lib/gcc-cross/aarch64-linux-gnu/13"

echo "C compiler: $(which aarch64-linux-gnu-gcc)"
echo "C++ compiler: $(which aarch64-linux-gnu-g++)"

# 修复头文件
echo ""
echo "[2/6] 修复头文件路径..."

# 确保 AArch64 的 curl 头文件存在
if [ ! -d /usr/aarch64-linux-gnu/include/curl ]; then
    echo "  创建 curl 头文件..."
    mkdir -p /usr/aarch64-linux-gnu/include/curl
    cp -r /usr/include/x86_64-linux-gnu/curl/*.h /usr/aarch64-linux-gnu/include/curl/ 2>/dev/null || true
fi

# 修复 stubs.h 问题
echo "  修复 stubs.h..."
mkdir -p /usr/aarch64-linux-gnu/include/gnu
cat > /usr/aarch64-linux-gnu/include/gnu/stubs.h << 'EOF'
/* This file is automatically generated.  DO NOT EDIT! */
/* This file is for AArch64 */
#include <gnu/stubs-lp64.h>
EOF

# 编译 yolov5_demo
echo ""
echo "[3/6] 编译 yolov5_demo..."
cd /project/Demo/yolov5_demo/cpp
rm -rf build_aarch64
mkdir -p build_aarch64
cd build_aarch64
cmake .. \
    -DCMAKE_TOOLCHAIN_FILE=../toolchain-aarch64.cmake \
    -DCMAKE_C_COMPILER=/usr/bin/aarch64-linux-gnu-gcc \
    -DCMAKE_CXX_COMPILER=/usr/bin/aarch64-linux-gnu-g++ \
    -DCMAKE_C_FLAGS="$CFLAGS" \
    -DCMAKE_CXX_FLAGS="$CXXFLAGS" \
    -DCMAKE_EXE_LINKER_FLAGS="$LDFLAGS" \
    -DCMAKE_SYSTEM_PROCESSOR=aarch64
make -j$(nproc) 2>&1 | tail -10
echo "  ✓ yolov5_demo 编译完成"

# 编译 AIChat_demo
echo ""
echo "[4/6] 编译 AIChat_demo/Client..."
cd /project/Demo/AIChat_demo/Client
rm -rf build_aarch64
mkdir -p build_aarch64
cd build_aarch64
cmake .. \
    -DTARGET_AARCH64=ON \
    -DCMAKE_C_COMPILER=/usr/bin/aarch64-linux-gnu-gcc \
    -DCMAKE_CXX_COMPILER=/usr/bin/aarch64-linux-gnu-g++ \
    -DCMAKE_C_FLAGS="$CFLAGS" \
    -DCMAKE_CXX_FLAGS="$CXXFLAGS" \
    -DCMAKE_EXE_LINKER_FLAGS="$LDFLAGS" \
    -DCMAKE_SYSTEM_PROCESSOR=aarch64
make -j$(nproc) 2>&1 | tail -10
echo "  ✓ AIChat_demo/Client 编译完成"

# 编译 DeskBot_demo
echo ""
echo "[5/6] 编译 DeskBot_demo..."
cd /project/Demo/DeskBot_demo
rm -rf build_aarch64
mkdir -p build_aarch64
cd build_aarch64
cmake .. \
    -DTARGET_AARCH64=ON \
    -DCMAKE_C_COMPILER=/usr/bin/aarch64-linux-gnu-gcc \
    -DCMAKE_CXX_COMPILER=/usr/bin/aarch64-linux-gnu-g++ \
    -DCMAKE_C_FLAGS="$CFLAGS" \
    -DCMAKE_CXX_FLAGS="$CXXFLAGS" \
    -DCMAKE_EXE_LINKER_FLAGS="$LDFLAGS" \
    -DCMAKE_SYSTEM_PROCESSOR=aarch64
make -j$(nproc) 2>&1 | tail -15
echo "  ✓ DeskBot_demo 编译完成"

# 复制依赖库到输出目录
echo ""
echo "[6/6] 复制依赖库到输出目录..."

AARCH64_LIB_DIR=/usr/aarch64-linux-gnu/lib_local
OUTPUT_BASE=/project/output/aarch64

# yolov5_demo 输出
YOLO_OUTPUT=$OUTPUT_BASE/yolov5_demo
mkdir -p $YOLO_OUTPUT
cp /project/Demo/yolov5_demo/cpp/build_aarch64/rknn_yolov5_demo $YOLO_OUTPUT/
# 复制模型文件
if [ -f /project/Demo/yolov5_demo/model/yolov5.rknn ]; then
    cp /project/Demo/yolov5_demo/model/yolov5.rknn $YOLO_OUTPUT/
fi
echo "  ✓ yolov5_demo 输出到 $YOLO_OUTPUT"

# AIChat_demo 输出
AICHAT_OUTPUT=$OUTPUT_BASE/AIChat_demo
mkdir -p $AICHAT_OUTPUT/bin
mkdir -p $AICHAT_OUTPUT/resources/snowboy/models
mkdir -p $AICHAT_OUTPUT/resources/audio
cp /project/Demo/AIChat_demo/Client/build_aarch64/AIChatClient $AICHAT_OUTPUT/bin/
cp /project/Demo/AIChat_demo/Client/third_party/snowboy/resources/common.res $AICHAT_OUTPUT/resources/snowboy/
cp /project/Demo/AIChat_demo/Client/third_party/snowboy/resources/models/echo.pmdl $AICHAT_OUTPUT/resources/snowboy/models/
cp /project/Demo/AIChat_demo/Client/third_party/audio/waked.pcm $AICHAT_OUTPUT/resources/audio/

# 复制 AIChat_demo 依赖库
mkdir -p $AICHAT_OUTPUT/lib
for lib in libjsoncpp.so.25 libopus.so.0 libportaudio.so.2 libopenblas.so.0; do
    if [ -f $AARCH64_LIB_DIR/$lib ]; then
        cp $AARCH64_LIB_DIR/$lib $AICHAT_OUTPUT/lib/
    fi
done
echo "  ✓ AIChat_demo 输出到 $AICHAT_OUTPUT"

# DeskBot_demo 输出（标准结构：bin/ 子目录）
DESKBOT_OUTPUT=$OUTPUT_BASE/DeskBot_demo
mkdir -p $DESKBOT_OUTPUT/bin

# 复制主程序和资源到 bin/ 目录
cp /project/Demo/DeskBot_demo/bin/main $DESKBOT_OUTPUT/bin/
cp /project/Demo/DeskBot_demo/bin/system_para.conf $DESKBOT_OUTPUT/bin/
cp /project/Demo/DeskBot_demo/bin/gaode_adcode.json $DESKBOT_OUTPUT/bin/
cp /project/Demo/DeskBot_demo/bin/cacert.pem $DESKBOT_OUTPUT/bin/

# 复制库文件
mkdir -p $DESKBOT_OUTPUT/bin/lib
cp -r /project/Demo/DeskBot_demo/bin/lib/* $DESKBOT_OUTPUT/bin/lib/ 2>/dev/null || true

# 复制模型和资源
mkdir -p $DESKBOT_OUTPUT/bin/model
cp -r /project/Demo/DeskBot_demo/bin/model/* $DESKBOT_OUTPUT/bin/model/ 2>/dev/null || true

mkdir -p $DESKBOT_OUTPUT/bin/third_party
cp -r /project/Demo/DeskBot_demo/bin/third_party/* $DESKBOT_OUTPUT/bin/third_party/ 2>/dev/null || true

# 确保所有依赖库都已复制
# libcurl.so.4 也会复制，但 run.sh 会智能选择使用系统版本还是自带版本
for lib in libjsoncpp.so.25 libopus.so.0 libportaudio.so.2 libopenblas.so.0 libasound.so.2 libjson-c.so.4 libcurl.so.4 librknnrt.so librknnmrt.so librga.so; do
    if [ -f $AARCH64_LIB_DIR/$lib ]; then
        cp $AARCH64_LIB_DIR/$lib $DESKBOT_OUTPUT/bin/lib/ 2>/dev/null || true
    fi
done
echo "  ✓ DeskBot_demo 输出到 $DESKBOT_OUTPUT"

# 创建启动脚本（自动修复依赖）
cat > $DESKBOT_OUTPUT/run.sh << 'EOF'
#!/bin/bash
# Echo-Mate DeskBot 启动脚本
# 自动处理库依赖兼容性问题

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"

# 颜色输出
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# 检测架构
ARCH=$(uname -m)
case "$ARCH" in
    aarch64) LIB_PATH="/usr/lib/aarch64-linux-gnu" ;;
    armv7l|armhf) LIB_PATH="/usr/lib/arm-linux-gnueabihf" ;;
    x86_64) LIB_PATH="/usr/lib/x86_64-linux-gnu" ;;
    *) LIB_PATH="/usr/lib" ;;
esac

# 检查并安装系统依赖
install_system_deps() {
    echo -e "${YELLOW}[检查系统依赖]${NC}"
    
    local deps_needed=""
    
    # 检查 libcurl4
    if ! ldconfig -p | grep -q "libcurl.so.4"; then
        deps_needed="$deps_needed libcurl4"
    fi
    
    # 检查 ALSA
    if ! ldconfig -p | grep -q "libasound.so.2"; then
        deps_needed="$deps_needed libasound2"
    fi
    
    if [ -n "$deps_needed" ]; then
        echo -e "${YELLOW}需要安装以下系统依赖:$deps_needed${NC}"
        
        # 检查是否有 sudo 权限
        if ! sudo -n true 2>/dev/null; then
            echo -e "${YELLOW}需要管理员权限安装依赖，请输入密码...${NC}"
        fi
        
        sudo apt-get update -qq
        sudo apt-get install -y -qq $deps_needed
        echo -e "${GREEN}✓ 系统依赖安装完成${NC}"
    else
        echo -e "${GREEN}✓ 系统依赖已满足${NC}"
    fi
}

# 智能处理 libcurl 库
# 策略：优先使用系统 libcurl，如果系统没有则使用自带版本
setup_libcurl() {
    echo -e "${YELLOW}[配置 libcurl]${NC}"
    
    local system_curl="$LIB_PATH/libcurl.so.4"
    local bundled_curl="$SCRIPT_DIR/bin/lib/libcurl.so.4"
    
    if [ -f "$system_curl" ]; then
        # 系统有 libcurl，优先使用系统版本
        echo -e "${GREEN}✓ 使用系统 libcurl: $system_curl${NC}"
        # 临时移除自带的 libcurl，避免冲突
        if [ -f "$bundled_curl" ]; then
            mv "$bundled_curl" "$bundled_curl.bak" 2>/dev/null || true
        fi
        # 设置库路径：系统库优先
        export LD_LIBRARY_PATH="$LIB_PATH:$SCRIPT_DIR/bin/lib:$LD_LIBRARY_PATH"
    else
        # 系统没有 libcurl，使用自带版本
        echo -e "${YELLOW}! 系统未安装 libcurl，使用自带版本${NC}"
        # 恢复自带的 libcurl（如果之前被备份）
        if [ -f "$bundled_curl.bak" ]; then
            mv "$bundled_curl.bak" "$bundled_curl" 2>/dev/null || true
        fi
        # 设置库路径：自带库优先
        export LD_LIBRARY_PATH="$SCRIPT_DIR/bin/lib:$LIB_PATH:$LD_LIBRARY_PATH"
    fi
}

# 检查程序依赖
check_program_deps() {
    echo -e "${YELLOW}[检查程序依赖]${NC}"
    
    local missing=$(ldd ./bin/main 2>/dev/null | grep "not found" | awk '{print $1}' || true)
    
    if [ -n "$missing" ]; then
        echo -e "${RED}✗ 以下依赖库缺失:${NC}"
        echo "$missing" | while read lib; do
            echo "  - $lib"
        done
        
        # 特殊处理：如果是 OpenLDAP 版本不匹配，给出明确提示
        if echo "$missing" | grep -q "OPENLDAP"; then
            echo ""
            echo -e "${YELLOW}提示: 检测到 OpenLDAP 版本不兼容${NC}"
            echo -e "${YELLOW}建议: 确保系统已安装 libcurl4，脚本会自动优先使用系统版本${NC}"
        fi
        
        return 1
    fi
    
    echo -e "${GREEN}✓ 所有依赖已满足${NC}"
    return 0
}

# 确保程序有执行权限
fix_permissions() {
    if [ ! -x ./bin/main ]; then
        echo -e "${YELLOW}[修复权限]${NC} 添加执行权限..."
        chmod +x ./bin/main
    fi
}

# 主程序
echo "========================================"
echo "    Echo-Mate DeskBot 启动器"
echo "========================================"
echo ""
echo "架构: $ARCH"
echo ""

# 步骤 1: 修复权限
fix_permissions

# 步骤 2: 安装系统依赖
install_system_deps

# 步骤 3: 智能配置 libcurl
setup_libcurl

# 步骤 4: 检查程序依赖
if ! check_program_deps; then
    echo ""
    echo -e "${RED}依赖检查失败，请手动解决上述问题${NC}"
    exit 1
fi

echo ""
echo -e "${GREEN}✓ 所有检查通过，启动 DeskBot...${NC}"
echo ""
cd bin && exec ./main "$@"
EOF
echo "  ✓ run.sh 创建完成"
chmod +x $DESKBOT_OUTPUT/run.sh

# 确保 main 有执行权限（使用 755 确保可读可执行）
chmod 755 $DESKBOT_OUTPUT/bin/main

# 确保所有库文件有读取权限
chmod 644 $DESKBOT_OUTPUT/bin/lib/*.so* 2>/dev/null || true

# 创建 README
cat > $OUTPUT_BASE/README.txt << 'EOF'
Echo-Mate AArch64 构建输出
==========================

目录结构:
├── yolov5_demo/
│   ├── rknn_yolov5_demo    # YOLOv5 可执行文件
│   └── yolov5.rknn         # 模型文件（如果有）
│
├── AIChat_demo/
│   ├── bin/
│   │   └── AIChatClient    # AIChat 客户端可执行文件
│   ├── lib/                # 依赖库
│   └── resources/          # 资源文件
│       ├── snowboy/
│       │   ├── common.res
│       │   └── models/echo.pmdl
│       └── audio/waked.pcm
│
└── DeskBot_demo/
    ├── run.sh              # 启动脚本（推荐）
    └── bin/                # 程序和资源目录
        ├── main            # 主程序
        ├── lib/            # 所有依赖库
        ├── model/          # YOLO 模型
        ├── third_party/    # 唤醒词资源
        ├── system_para.conf # 系统配置
        ├── gaode_adcode.json # 城市代码
        └── cacert.pem      # SSL 证书

运行方法:
1. DeskBot_demo（推荐）:
   cd DeskBot_demo
   ./run.sh
   
   脚本会自动：
   - 检查并安装系统依赖（libcurl4、libasound2 等）
   - 自动修复库冲突
   - 检查所有依赖是否满足
   
   或手动运行（不推荐）:
   export LD_LIBRARY_PATH=/usr/lib/aarch64-linux-gnu:./bin/lib:$LD_LIBRARY_PATH
   ./bin/main

2. AIChat_demo:
   cd AIChat_demo
   export LD_LIBRARY_PATH=./lib:$LD_LIBRARY_PATH
   ./bin/AIChatClient

3. yolov5_demo:
   cd yolov5_demo
   ./rknn_yolov5_demo
   （需要目标设备安装 librknnrt.so）

依赖说明:
- 所有必要的依赖库已包含在 lib/ 目录中
- 如果目标设备上已安装相同版本的库，可以不使用自带的 lib/
- RKNN 运行时 (librknnrt.so) 需要目标设备支持 Rockchip NPU
EOF

echo "  ✓ 创建启动脚本和 README"

echo ""
echo "=========================================="
echo "编译和部署准备完成!"
echo "=========================================="
echo ""
echo "输出目录: $OUTPUT_BASE"
echo ""
echo "文件列表:"
find $OUTPUT_BASE -type f -name "*.sh" -o -name "*.txt" -o -name "main" -o -name "AIChatClient" -o -name "rknn_yolov5_demo" | head -10
echo ""
echo "验证文件类型:"
echo "  yolov5_demo:  $(file $YOLO_OUTPUT/rknn_yolov5_demo | grep -o 'ARM aarch64' || echo '未知')"
echo "  AIChat_demo:  $(file $AICHAT_OUTPUT/bin/AIChatClient | grep -o 'ARM aarch64' || echo '未知')"
echo "  DeskBot_demo: $(file $DESKBOT_OUTPUT/main | grep -o 'ARM aarch64' || echo '未知')"
echo ""
echo "部署方法:"
echo "  1. 将整个 $OUTPUT_BASE 目录复制到目标设备"
echo "  2. 在目标设备上运行 DeskBot_demo/run.sh"
echo ""
echo "或使用 scp 复制到远程设备:"
echo "  scp -r $OUTPUT_BASE/DeskBot_demo user@lubancat:~/"
echo "  ssh user@lubancat 'cd ~/DeskBot_demo && ./run.sh'"
echo ""
